#!/usr/bin/env bash
set -e # halt script on error

pip install -r script/requirements.txt
python script/deployment-setup.py
node_modules/gulp/bin/gulp.js ci-build

bundle exec jekyll build
gem build jekyll-sleek.gemspec
